# Generated by Django 5.0 on 2024-01-01 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_qty', models.PositiveBigIntegerField(default=1)),
                ('total_price', models.PositiveBigIntegerField()),
                ('order_status', models.CharField(default='pending', max_length=150)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_web.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_web.product')),
            ],
        ),
    ]
